### ISSUE TITLE
add scroll navigation

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/react-aframe-volume-renderer#12]

**Comment by mirestrepo** [comment]
The scroll navigation that have used in the past is: https://github.com/react-component/scroll-anim
The example app where I used it 
https://datasci.brown.edu/socio-eco-project/
The corresponding repo/code live here... let me know if you can't see it
https://github.com/brown-ccv/georeg-web-app/blob/master/src/components/ScrollNavigation.js

**Comment by theklam** [comment]
- move logos left, nav on right (both on the same nav bar) 
- fix css for the about section
- add some type of instructions on how to use the app

**Comment by theklam** [comment]
from fernando: 
- colors: https://www.brown.edu/university-communications/digital/university-theme
- examplenav: https://brown-ccv.github.io/ccv-status-frontend/

**Comment by theklam** [comment]
added and merged into the develop branch!
