### ISSUE TITLE
highlight nav bar elements and rename link to viewer

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/react-aframe-volume-renderer#40]
highlight nav bar elements and rename link to viewer.

**Comment by theklam** [comment]
- renamed link to viewer to "Home"
- I am running into trouble with highlighting the navbar elements. Background-color changes look off, so I am opting for a text-color change instead but it's not working.

**Comment by theklam** [comment]
- the navbar works a lot better with the native bootstrap linking rather than using the (link, element) type of stuff b/c it is from a different library, i think. 
- the only con with the bootstrap native linking is that I need to figure out how to do smooth scrolling with it.

**Comment by theklam** [comment]
nvm! I figured it out! this is done!
